travis:
  secure:
    BINSTAR_TOKEN: e/TCPPxmou5WHc1enJ/eo7BuiaerYY+bFjLcZZwjERb7XifXO7q3gunFFLMvyU/l9RtqLLyRXL7iDEqojRRP1Je2A5GbMfUPj3HuL+uUFx6Tb6Y8q0M9TQo2KEwhwxJQfr1ZzcReIFY6ToYGQBUcOMqLG6K8l64Fl91m1ozxAFR84uAYz23uunOe/5Dce0C9Nw0SBaRMmbevVeg+rLmqEcwG8kZMW5ExBEnih/U+ioXAUy12n17VSyswQEdSs2v/RUXD0+Kta47Xu3DgOajhST/TXcCXDj3rsPi6Gd/Ch+qoWaq5eMT9+0W5N/UE2OvcehmwRrm/wU7vdemQrjm7E6c6CBjpP2KOSgtop9CXht6Xu+Qo5lTocEbSTzLTZE0kZ82wxynmNy+PL/Dn+2wEZTWKW1jV5O2O0tpQBMeuYXV+brOwuz0arnuHTCjmO5UfMlfH0VtUob8W8wgmMHeeQM+OEnjiQPbzADONI9+mCzTQ0Z2KsiHgLd/aZaP8m885cM20XXW2CA5pnZdvbVOHk92gTi86bhEVqjuOFXLPKhb33JEiP4GRYfeS2BnolU4mpzSxYShQ+/tV1iDSY2PF31BBmoHPjsiYbTxBoDj0mTs+pzAmTqAhJl/oZYETy16KFlkZ9keefzvjn7fhTzUKTUoNZYc6ef9e57zvgH13RlI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
